// This file is generated by Firebase Genkit.
// Generated on: {{generated_on}}
'use server';
/**
 * @fileOverview Generates a reminder for database backups.
 *
 * - generateDatabaseBackupReminder - A function that generates a database backup reminder.
 * - GenerateDatabaseBackupReminderInput - The input type for the generateDatabaseBackupReminder function.
 * - GenerateDatabaseBackupReminderOutput - The return type for the generateDatabaseBackupReminder function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateDatabaseBackupReminderInputSchema = z.object({
  lastBackupDate: z.string().describe('The date of the last database backup.'),
  backupIntervalDays: z.number().describe('The interval in days between database backups.'),
});
export type GenerateDatabaseBackupReminderInput = z.infer<typeof GenerateDatabaseBackupReminderInputSchema>;

const GenerateDatabaseBackupReminderOutputSchema = z.object({
  reminder: z.string().describe('The database backup reminder message.'),
});
export type GenerateDatabaseBackupReminderOutput = z.infer<typeof GenerateDatabaseBackupReminderOutputSchema>;

export async function generateDatabaseBackupReminder(input: GenerateDatabaseBackupReminderInput): Promise<GenerateDatabaseBackupReminderOutput> {
  return generateDatabaseBackupReminderFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateDatabaseBackupReminderPrompt',
  input: {schema: GenerateDatabaseBackupReminderInputSchema},
  output: {schema: GenerateDatabaseBackupReminderOutputSchema},
  prompt: `You are a helpful assistant reminding a non-technical admin to create database backups.

The last database backup was on {{lastBackupDate}}. The recommended backup interval is {{backupIntervalDays}} days.

Generate a reminder message to the admin, urging them to create a database backup if the interval has passed. The reminder should be friendly but firm, emphasizing the importance of regular backups to prevent data loss.`,
});

const generateDatabaseBackupReminderFlow = ai.defineFlow(
  {
    name: 'generateDatabaseBackupReminderFlow',
    inputSchema: GenerateDatabaseBackupReminderInputSchema,
    outputSchema: GenerateDatabaseBackupReminderOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
